#!/usr/bin/env python
from socket import socket, AF_UNIX, SOCK_STREAM
import sys

from keyholer import conf
from keyholer.client import KeyholerClient


if __name__ == '__main__':
    data = ' '.join(sys.argv[1:])

    c = KeyholerClient()
    print c.login('zwhite')
    code = raw_input('Code: ')
    print c.verify('zwhite', code)
    #print c.add_key('zwhite', code, 'ssh-dss AAAAB3NzaC1kc3MAAACBALU5xUTKDIJ/x94sMw7Hnj0fEKIzhgXyUa20yLNBnAmIG9mOTb1ucZRsn5zO/tVToL/US5I7ns9l8hZw3JsU6qDEA6jtlsO5JmtowsT0mmiPGxrnlAKI5CtL7pPZ9G9KZCAM74XV3dcq1jNiQ0HH+Hhh2Rgof50py0po2HNinHbfAAAAFQDSInXWrwIRF+sqEn49friyzM75ZQAAAIAozydrNdkCVsxCsLS3rthf/CB1pZtJ0fLmpTvY+F4VPi+Tfw2knZSGMJV2hvu7UoydkulkxLxkspLK5NZckppkWZE/3dyXlYqsaiwNS1QAv2ICAqRFEo60YtaOwdmOg4yj7WZQ1egaCbIZUChQ/TK4DBnx8Bvf8jv19TWv6yrsDgAAAIBGGaNuaLHD0rZHe7Yu6Lx55ddEJ5ZMFB7bJFCfnGZqBwtJwLzHXvTAFqY761X47bTA+U5Hv83b39Tx5x7/tX2mBSZAhnz4qcNEXW3jH+kPyOFh+tpzZkUkAmsLjuSXlh4/glHPDE5cqDW9w7N9C9/6nV6IxVyOc774EpK9C1ux8A== zwhite@XXX.com')
