#!/usr/bin/env python
from keyholer.client import KeyholerClient


if __name__ == '__main__':
    c = KeyholerClient()
    print c.login('zwhite')
    code = raw_input('Code: ')
    print c.verify('zwhite', code)
    # print c.add_key('zwhite', code, '')
